---
- name: check node version
  shell: |
   /usr/local/bin/node --version | grep -q 'v0.12.7'; echo $?
  register: result
  ignore_errors: True

- name: install nodejs
  shell: |
    wget http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
    tar xvf node-v0.12.7.tar.gz
    rm node-v0.12.7.tar.gz
    cd node-v0.12.7
    ./configure
    make
    make install
  when: result.stdout != '0'
