---
- name: check node version
  shell: |
   /usr/local/bin/node --version | grep -q '{{ node_version }}'; echo $?
  register: result
  ignore_errors: True
  changed_when: False

- name: install nodejs
  shell: |
    wget http://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}.tar.gz
    tar xvf node-{{ node_version }}.tar.gz
    rm node-{{ node_version }}.tar.gz
    cd node-{{ node_version }}
    ./configure
    make
    make install
  when: result.stdout != '0'
