---
- name: git clone node
  shell: |
    rm -rf node
    git clone https://github.com/tomox1001/node.git

- name: npm install
  shell: |
    cd node
    npm i

- name: pm2 install
  shell: |
    sudo npm i -g pm2
