---
- name: git clone node
  shell: |
    rm -rf node
    git clone https://github.com/minus-tsunderation/node.git

- name: npm install
  shell: |
    cd node
    npm i

- name: minify css
  shell: |
    cd node
    grunt cssmin
    sed -i -e "s/.css/.min.css/g" views/*.ect
