---
#- name: install nginx
#  shell: |
#    mkdir nginx
#    cd /etc/nginx
#    wget http://nginx.org/download/nginx-1.9.6.tar.gz
#    tar xvfz nginx-1.9.6.tar.gz
#    cd nginx-1.9.6/
#    ./configure --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module
#    make
#    make install

- name: put nginx.d
  template: src=nginx.d.j2 dest=/etc/init.d/nginx

- name: put nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: start nginx
  shell: |
    sudo /etc/init.d/nginx restart

- stat: path=./linux_amd64.zip
  register: is_file

- name: install kataribe
  shell: |
    wget https://github.com/matsuu/kataribe/releases/download/v0.3.0/linux_amd64.zip
    unzip linux_amd64.zip
  when: is_file.stat.md5 is not defined
