---
- name: install nginx
  yum: name=nginx state=present

- name: put nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

#- name: put conf.d/default.conf
#  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
#
#- name: put conf.d/virtual.conf
#  template: src=virtual.conf.j2 dest=/etc/nginx/conf.d/virtual.conf

- name: set auto start nginx
  command: chkconfig nginx on
- name: restart nginx
  command: service nginx restart

- stat: path=./linux_amd64.zip
  register: is_file

- name: install kataribe
  shell: |
    wget https://github.com/matsuu/kataribe/releases/download/v0.3.0/linux_amd64.zip
    unzip linux_amd64.zip
  when: is_file.stat.md5 is not defined
