---
- name: install nginx
  yum: name=nginx state=present

- name: put nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

#- name: put conf.d/default.conf
#  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
#
#- name: put conf.d/virtual.conf
#  template: src=virtual.conf.j2 dest=/etc/nginx/conf.d/virtual.conf

- name: set auto start nginx
  command: chkconfig nginx on
- name: restart nginx
  command: service nginx restart
